name: Twitter fetch likes to Telegram

on: 
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: fetchLikes
  schedule:
    - cron:  '1 * * * *'

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  fetch:
    # Name the Job
    name: getLatest
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 20.x

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create .env file
        run: |
          touch .env
          echo TELEGRAM_CHANNELBOT=${{ secrets.TELEGRAM_CHANNELBOT }} >> .env
          echo TWITTER_AUTHORIZATION=${{ secrets.TWITTER_AUTHORIZATION }} >> .env
          echo TWITTER_X_CSRF_TOKEN=${{ secrets.TWITTER_X_CSRF_TOKEN }} >> .env
          echo TWITTER_COOKIE=${{ secrets.TWITTER_COOKIE }} >> .env
          echo TELEGRAM_CHATID=${{ secrets.TELEGRAM_CHATID }} >> .env
          echo GIST_TOKEN=${{ secrets.GIST_TOKEN }} >> .env
          echo GIST_ID=${{ secrets.GIST_ID }} >> .env
          echo GIST_FILE=${{ secrets.GIST_FILE }} >> .env
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: start job
        run: yarn && yarn fetch
      
